### PR TITLE
Adding option to disable extra rolls

### PR DESCRIPTION
**Pull request by Rhozero**
Just a suggested change to enable or disable extra rolls when the roller class is created.

### CODE REVIEW

**Comment by orels1** [comment]
How would you use that parameter on the user's end tho?

**Comment by Rhozero** [comment]
I am assuming that when they setup the class with the bot. Line 123-124. I am not sure how it works to be honest.

**Comment by Rhozero** [comment]
[roll.zip](https://github.com/orels1/ORELS-Cogs/files/1162822/roll.zip)

Here is a revision that instead uses a toggle command to change the extra rolls on or off

**Comment by orels1** [comment]
This is a nice solution, although it will work cross-server. so if your bot is on many servers - it would toggle for everyone. It would be nice to have like a dict with a sctructure like this

```python
extraRolls = {
  '<serverid>': True,
  '<serverid>': False
}
```

You get the point. Should be easy to implement and you can easily check in the same `if` statement for something like `extraRolls[ctx.message.server]` or smth

**Comment by Rhozero** [comment]
That's pretty brilliant. I was curious how it would behave if the bot was on multiple servers. Also if you have two bots on the same server, you could probably add a parameter to specify which bot you want to change the setting on.

**Comment by orels1** [comment]
Hmm, you shouldn't really run 2 bots with the same prefix on the same server. That's not too safe =)

**Pull request closed without merging**
